//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aprendiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aprendiz()
        {
            this.Ingreso = new HashSet<Ingreso>();
        }
    
        public int idAprendiz { get; set; }
        public Nullable<int> numeroFicha { get; set; }
        public string NombreAprendiz { get; set; }
        public string tipoDocumento { get; set; }
        public string EstadoAprendiz { get; set; }
        public byte[] Huella { get; set; }
        public string UsuarioAprendiz { get; set; }
        public string ContraseñaAprediz { get; set; }
    
        public virtual Ficha Ficha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingreso> Ingreso { get; set; }
    }
}
