//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int numeroIngreso { get; set; }
        public Nullable<int> idInstructor { get; set; }
        public Nullable<int> idAprendiz { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.TimeSpan> horaIngreso { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public Nullable<System.TimeSpan> horaSalida { get; set; }
    
        public virtual Aprendiz Aprendiz { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
