//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquina
    {
        public int numeroMaquina { get; set; }
        public Nullable<int> idInstructor { get; set; }
        public string NombreMaquina { get; set; }
        public string EstadoMaquina { get; set; }
    
        public virtual Instructor Instructor { get; set; }
    }
}
