//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutina
    {
        public int idRutina { get; set; }
        public Nullable<int> idPublicacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string nombreRutina { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
    }
}
